### ISSUE TITLE
Build fails on multi-arch images with "docker exporter does not currently support exporting manifest lists"

### ISSUE THREAD

**Issue by pjmpsu** [concourse/oci-build-task#85]
I am able to successfully build linux/arm or linux/amd64 images. When attempting to pass in multiple params to IMAGE_PLATFORM like so `IMAGE_PLATFORM: linux/amd64,linux/arm64`. The result is as follows:

```
#23 exporting to oci image format
#23 ERROR: docker exporter does not currently support exporting manifest lists
------
 > exporting to oci image format:
------
error: failed to solve: docker exporter does not currently support exporting manifest lists
FATA[0046] failed to build: build: exit status 1        
FATA[0046] failed to run task: exit status 1
```

**Comment by cheeseball212** [comment]
This is a great idea! Adding multi arch support would be very beneficial and streamline processes. We have employees using new mac systems with Apple's M1 processor that have reported their docker containers no longer work. We have since been looking for a way to support multiple platforms in the same image and this could certainly help in achieving that.

**Comment by joaosa** [comment]
I am also very interested in this, but it seems like an upstream issue. Look [here](https://github.com/concourse/oci-build-task/blob/7068da671da575c4d781352f07a0dfe1a7dfff97/task.go#L129) and [here](https://github.com/docker/buildx/blob/3adca1c17db9439fb94499ccef62f6a40dcaf899/build/build.go#L491)

**Comment by holgerstolzenberg** [comment]
This is indeed something that becomes more and more necessary. With the emerging ARM technology introduce by Apple M1 chipset, more and more of our developers are in need of a multi-arch build for local development. Using hard coded architecture bound tags `my-image:1.2.3-linux-amd64` ist not  feasible, as this changes from dev env to dev env.

Currently we are using a variant of the `docker-image` resource (`ljfranklin/docker-buildx-resource`) that supports `buildx`, but the `docker-image` resource is deprecated and everyone is encouraged to migrate to `oci-build-task` and `registry-image` resource. 

Also - lastly experienced some problems related to the `lists.manifest.json` in Artifactory using this resource, but could not clarify upon now if it is related to the resource or Artifactory, what is our artifact storage system.

We really would want to migrate to `oci-build-task` and `registry-image` resource for various reasons:
- documentation
- stability
- performance
- caching
- maintenance
- being official Concourse resources
but not being able to do multi-arch builds is a showstopper for us.

As already mentioned, the build already runs for multiple architectures, it is _only_ a matter of the exporter to support it.

Would be great to see that coming soon. ✌️

**Comment by dackroyd** [comment]
Got further with this by running a custom build of the `oci-build-task`, where its `--output` is set to `"type=oci,dest="+imagePath`. The image builds successfully with `buildctl`, however the final steps of the `oci-build-task` fail because it requires a `manifest.json` to be present in the tarball, which the `oci` format does not include.

Having then bypassed that section as well, and attempting to use the resulting tarball with the `registry-image-resource`, the same `manifest.json` failure pops up. Managed to dig up an old open issue from there pointing to the problem: https://github.com/concourse/registry-image-resource/issues/49#issuecomment-524094484

> [...] would it be accurate to say the current oci format (supported by in), while having Docker-specific manifest.json in it, is still valid OCI at least? i.e. it's a superset?

I suspect that being able to properly produce the `oci` output via this `oci-build-task`, and the `registry-image-resource` also supporting the `oci` format could resolve the issue of multi-arch support?

**Comment by dackroyd** [comment]
I believe this is resolved by https://github.com/concourse/oci-build-task/pull/93 and https://github.com/concourse/registry-image-resource/pull/321. The later appears to have made it into `registry-image-resource` release v1.6.0: https://github.com/concourse/registry-image-resource/compare/v1.5.1...v1.6.0, while `oci-build-task` has not yet cut a release since the corresponding change went in.

**Comment by kuznero** [comment]
After almost a year, I still have this problem. Any news on how to work it around?

**Comment by brunellie** [comment]
To fix this just add `OCI_OUTPUT: true` in the task params.

**Comment by scottwsides** [comment]
> To fix this just add `OUTPUT_OCI: true` in the task params.

Could you be more specific? Where are these 'task params'? What does your final docker buildx build.... command look like

**Comment by meezaan** [comment]
@brunellie this worked for me.

@scottwsides see screenshot.

<img width="688" alt="Screenshot 2024-05-03 at 10 39 47 AM" src="https://github.com/concourse/oci-build-task/assets/1839282/5dc86b00-0590-4ac0-a7c5-f1e561adf468">

**Comment by kolserdav** [comment]
I use `--output type=image` instead of `--output type=docker` and it works for me:
```sh
docker buildx build --platform="linux/arm64,linux/amd64"  --output="type=image"
```

**Comment by brunellie** [comment]
@scottwsides This is an issue on the Concourse oci-build-task. I was mentioning the params field in the generic Concourse task configuration. I'm using the task to build multi-arch so there's no command to show

**Comment by baritarek** [comment]
I am using the M3 and this command worked for me
docker buildx build --platform linux/amd64,linux/arm64 -t <dockerimage>:multi-arch --output type=image,dest=./<dockerimage>.tar .
